# Generated by Django 3.1.7 on 2021-05-15 14:47

from django.db import migrations, models
import django.db.models.deletion


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# balloting.migrations.0002_superuser


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ballot",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_text", models.CharField(max_length=100)),
                (
                    "opening_date",
                    models.DateTimeField(verbose_name="opening date and time"),
                ),
                (
                    "closing_date",
                    models.DateTimeField(verbose_name="closing date and time"),
                ),
                (
                    "url_fragment_text",
                    models.CharField(
                        default="default",
                        help_text="Slug text to be used in the urls for this ballot",
                        max_length=40,
                    ),
                ),
                (
                    "url_summary_fragment_text",
                    models.CharField(
                        default="48245591",
                        help_text="Slug text to be used in the summary url for this ballot",
                        max_length=40,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.CharField(max_length=100)),
                (
                    "ballot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="balloting.ballot",
                    ),
                ),
                (
                    "order_int",
                    models.IntegerField(default=1, verbose_name="Question order"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("choice_text", models.CharField(max_length=100)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="balloting.question",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Voter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_text",
                    models.EmailField(max_length=254, verbose_name="Email address"),
                ),
                (
                    "description_text",
                    models.CharField(
                        help_text="A descriptive note for this voter",
                        max_length=200,
                        verbose_name="Description",
                    ),
                ),
                (
                    "emailed_bool",
                    models.BooleanField(
                        default=False,
                        verbose_name="Voter has been emailed voting instructions",
                    ),
                ),
                (
                    "url_fragment_text",
                    models.CharField(
                        blank=True, default=None, max_length=20, null=True, unique=True
                    ),
                ),
                (
                    "ballot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="balloting.ballot",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "choice",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="balloting.choice",
                    ),
                ),
                (
                    "voter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="balloting.voter",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="ballot",
            name="url_fragment_text",
            field=models.CharField(
                help_text="Slug text to be used in the urls for this ballot",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="ballot",
            name="url_summary_fragment_text",
            field=models.CharField(
                help_text="Slug text to be used in the summary url for this ballot",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="order_int",
            field=models.IntegerField(verbose_name="Question order"),
        ),
    ]
