# Generated by Django 3.1.7 on 2021-03-13 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balloting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballot',
            name='url_fragment_text',
            field=models.CharField(default='default', help_text='Slug text to be used in the urls for this ballot', max_length=40),
            preserve_default=False,
        ),
    ]
