# Generated by Django 3.1.7 on 2021-03-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("balloting", "0002_ballot_url_fragment_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="choice",
            name="order_int",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
