# Generated by Django 3.1.7 on 2021-03-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balloting', '0003_choice_order_int'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='order_int',
        ),
        migrations.AddField(
            model_name='question',
            name='order_int',
            field=models.IntegerField(default=1, verbose_name='Question order'),
            preserve_default=False,
        ),
    ]
