# Generated by Django 3.1.7 on 2021-03-14 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('balloting', '0004_auto_20210313_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_text', models.EmailField(max_length=254)),
                ('description_text', models.CharField(help_text='A descriptive note for this voter', max_length=200)),
                ('emailed_bool', models.BooleanField(default=False)),
                ('url_fragment_text', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('ballot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balloting.ballot')),
            ],
        ),
    ]
